[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.27"
tokio = {version ="1.32.0", features=["full"]}
tokio-tungstenite = "0.20.0"
