services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpass
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./initFiles:/docker-entrypoint-initdb.d
    ports:
      - 6000:5432
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "your@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "yourpass"
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  pgdata:
  pgInit:
     driver: local

